export const GET_PROFILES = "GET_PROFILES";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const UPDATE_RECOMMENDATIONS = "UPDATE_RECOMMENDATIONS";
