export const dummyUsers = [
  {
    _id: 1,
    avatar: "https://robohash.org/quodtemporequis.png?size=100x100&set=set1",
    first_name: "Cathleen",
    last_name: "Loach",
    role: "Information Systems Manager",
    introduction:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. ",
    email: "cloach0@jugem.jp",
    personalSite: "yale.edu",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 5,
  },
  {
    _id: 2,
    avatar: "https://robohash.org/natusquaeratin.png?size=100x100&set=set1",
    first_name: "Brandy",
    last_name: "Sackett",
    role: "Assistant Professor",
    introduction:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    email: "bsackett1@ask.com",
    personalSite: "wordpress.com",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 15,
  },
  {
    _id: 3,
    avatar: "https://robohash.org/utducimusculpa.png?size=100x100&set=set1",
    first_name: "Grayce",
    last_name: "Keohane",
    role: "Environmental Specialist",
    introduction:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    email: "gkeohane2@gov.uk",
    personalSite: "google.com.au",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 12,
  },
  {
    _id: 4,
    avatar: "https://robohash.org/estdoloraut.png?size=100x100&set=set1",
    first_name: "Ruy",
    last_name: "Scriviner",
    role: "Mechanical Systems Engineer",
    introduction:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. ",
    email: "rscriviner3@dot.gov",
    personalSite: "sourceforge.net",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 21,
  },
  {
    _id: 5,
    avatar: "https://robohash.org/eosmaximeatque.png?size=100x100&set=set1",
    first_name: "Rhoda",
    last_name: "Brandreth",
    role: "Pharmacist",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. ",
    email: "rbrandreth4@huffingtonpost.com",
    personalSite: "jalbum.net",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 18,
  },
  {
    _id: 6,
    avatar: "https://robohash.org/fugitvoluptatemcum.png?size=100x100&set=set1",
    first_name: "Gabey",
    last_name: "Bardill",
    role: "Computer Systems Analyst III",
    introduction:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    email: "gbardill5@sourceforge.net",
    personalSite: "alibaba.com",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 28,
  },
  {
    _id: 7,
    avatar:
      "https://robohash.org/sequicorruptiquibusdam.png?size=100x100&set=set1",
    first_name: "Karole",
    last_name: "Elliker",
    role: "Legal Assistant",
    introduction:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. ",
    email: "kelliker6@slideshare.net",
    personalSite: "edublogs.org",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 8,
  },
  {
    _id: 8,
    avatar: "https://robohash.org/quoddoloremut.png?size=100x100&set=set1",
    first_name: "Axe",
    last_name: "Origan",
    role: "Quality Engineer",
    introduction:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. ",
    email: "aorigan7@barnesandnoble.com",
    personalSite: "abc.net.au",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 36,
  },
  {
    _id: 9,
    avatar:
      "https://robohash.org/voluptatemvoluptasiure.png?size=100x100&set=set1",
    first_name: "Edyth",
    last_name: "Demeter",
    role: "Computer Systems Analyst I",
    introduction:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.",
    email: "edemeter8@networksolutions.com",
    personalSite: "yale.edu",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 6,
  },
  {
    _id: 10,
    avatar: "https://robohash.org/temporequiavelit.png?size=100x100&set=set1",
    first_name: "Trumaine",
    last_name: "Kleeborn",
    role: "Information Systems Manager",
    introduction:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    email: "tkleeborn9@patch.com",
    personalSite: "opera.com",
    linkedin: "https://www.linkedin.com",
    github: "https://www.github.com",
    instagram: "https://www.instagram.com",
    recommendations: 3,
  },
];
